[package]
name = "rust-app"
version = "0.0.1"
authors = ["jonored", "yhql"]
edition = "2018"
autobins = false
resolver = "2"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
ledger-parser-combinators = "0.1.0"
ledger-log = { git = "https://github.com/obsidiansystems/ledger-platform" }
ledger-crypto-helpers = { git = "https://github.com/ea-nasir/ledger-crypto-helpers" }
zeroize = { version = "1.5.2", default-features = false }
pin-project = "1.0.10"
num-traits = { version = "0.2.14", default-features = false }
num-derive = "0.3.3"

# Pass --features speculos,ledger-log/log_info (or log_trace, etc) to enable
# speculos logging and change log level.
[features]
default = [ ]
speculos = [ "nanos_sdk/speculos", "ledger-log/speculos", "ledger-log/log_error", "ledger-parser-combinators/logging" ]
extra_debug = ["ledger-log/log_trace"]

[target.thumbv6m-none-eabi.dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" } 
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" } 
ledger-prompts-ui = { git = "https://github.com/ea-nasir/ledger-prompts-ui" }
ledger-async-block = "0.1.0"

[target.thumbv6m-none-eabi.dev-dependencies.nanos_sdk]
git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git"
features = [ "speculos" ]

[dev-dependencies]
testmacro = { git = "https://github.com/yhql/testmacro"}

[build-dependencies]
proto-gen = { git = "https://github.com/obsidiansystems/ledger-parser-combinators", branch = "add-gen" }
tempfile = "3.3"

[[bin]]
name = "rust-app"
test = false
path = "bin-src/main.rs"

[patch."https://github.com/LedgerHQ/ledger-nanos-sdk.git".nanos_sdk]
git = "https://github.com/obsidiansystems/ledger-nanos-sdk.git"
branch = "use-ambient-compiler-and-target"

[patch.crates-io]
ledger-parser-combinators = { git = "https://github.com/obsidiansystems/ledger-parser-combinators", branch = "add-gen" }
ledger-async-block = { git = "https://github.com/obsidiansystems/ledger-platform", branch = "wip-async-overridable" }

[package.metadata.nanos]
name = "Rust App"
path = "44'/535348'"
curve = "ed25519"
flags = "0"
icon = "crab.gif"
